import {ROOMS,clock,minutes} from './catalog';
const xml=(s:any)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!)).replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'');
export const folio=(b:any)=>`C-${String(b.folio).padStart(6,'0')}`;
export const roomName=(id:string)=>ROOMS.find(r=>r.id===id)?.name||'Sin asignar';
export const stateName=(s:string)=>({confirmed:'Confirmada',waiting:'En espera',attended:'Atendida',cancelled:'Cancelada',deleted:'Eliminada'}[s]||s);
const mx=(s:string)=>s?new Date(s).toLocaleString('es-MX',{timeZone:'America/Mexico_City'}):'';
export function exportSheets(data:any,audit:any[]){
 return [
 {name:'Citas',rows:[['Folio','Cliente','Fecha','Hora','Fin','Duración (min)','Personas totales','Discapacidad','Sala','Estado','Atiende','Equipo','Operaciones','Notas','Creó','Creación CDMX','Modificó','Modificación CDMX','Motivo'],...data.bookings.map((b:any)=>[folio(b),b.client,b.date,b.time,clock(minutes(b.time)+b.duration),b.duration,b.people,b.accessibility?'Sí':'No',roomName(b.room),stateName(b.status),b.attendeeName,b.teamName,b.operations.map((o:any)=>o.name).join('; '),b.notes,b.createdBy,mx(b.createdAt),b.updatedBy,mx(b.updatedAt),b.reason])]},
 {name:'Operaciones por cita',rows:[['Folio','Fecha','Estado','Materia','Operación','Atiende','Equipo'],...data.bookings.flatMap((b:any)=>b.operations.map((o:any)=>[folio(b),b.date,stateName(b.status),o.matter,o.name,b.attendeeName,b.teamName]))]},
 {name:'Auditoría',rows:[['ID','Fecha y hora CDMX','Fecha y hora UTC','Usuario','Acción','Registro','Antes','Después'],...audit.map((a:any)=>[a.id,mx(a.at),a.at,a.actor,a.action,a.entity,a.before,a.after])]},
 {name:'Catálogo',rows:[['ID','Materia','Operación','Activa'],...data.operations.map((o:any)=>[o.id,o.matter,o.name,o.active?'Sí':'No'])]},
 {name:'Bloqueos vigentes',rows:[['Sala','Fecha','Inicio','Fin','Motivo','Creó'],...data.blocks.map((b:any)=>[roomName(b.room),b.date,b.start,b.end,b.reason,b.createdBy])]}
 ];
}
function save(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
export function csvExport(sheets:any[]){const quote=(v:any)=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"';const rows=sheets.flatMap(s=>[[s.name],...s.rows,[]]);save(new Blob(['\ufeff'+rows.map(row=>row.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),'agenda-log-completo.csv');}
export async function xlsxExport(sheets:any[]){
 const {zipSync,strToU8}=await import('fflate');const files:any={};const put=(p:string,s:string)=>files[p]=strToU8(s);const header='<?xml version="1.0" encoding="UTF-8" standalone="yes"?>';
 put('[Content_Types].xml',header+`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`);
 put('_rels/.rels',header+'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');
 put('xl/workbook.xml',header+`<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((s,i)=>`<sheet name="${xml(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`);
 put('xl/_rels/workbook.xml.rels',header+`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}</Relationships>`);
 const col=(n:number)=>{let s='';for(n++;n>0;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;};
 sheets.forEach((s,i)=>put(`xl/worksheets/sheet${i+1}.xml`,header+`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${s.rows[0].map((_:any,j:number)=>`<col min="${j+1}" max="${j+1}" width="24" customWidth="1"/>`).join('')}</cols><sheetData>${s.rows.map((row:any[],j:number)=>`<row r="${j+1}">${row.map((v,k)=>typeof v==='number'?`<c r="${col(k)}${j+1}"><v>${v}</v></c>`:`<c r="${col(k)}${j+1}" t="inlineStr"><is><t xml:space="preserve">${xml(v)}</t></is></c>`).join('')}</row>`).join('')}</sheetData><autoFilter ref="A1:${col(s.rows[0].length-1)}${s.rows.length}"/></worksheet>`));
 save(new Blob([zipSync(files) as BlobPart],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),'agenda-despacho.xlsx');
}
export function printBooking(b:any,name:string,popup?:Window|null){
 const w=popup||window.open('','_blank');if(!w)return false;
 w.document.open();w.document.write(`<!doctype html><html lang="es"><head><title>${xml(folio(b))} · Confirmación</title><style>body{font:16px system-ui;color:#172b49;margin:50px}header{border-bottom:3px solid #172b49;padding-bottom:25px}h1{font:36px Georgia;margin:12px 0}.folio{float:right}dt{font-size:12px;text-transform:uppercase;color:#52657b;margin-top:24px}dd{margin:6px 0;font-size:20px}footer{margin-top:40px;border-top:1px solid #ccd5df;padding-top:15px;font-size:12px}button{padding:10px;margin-bottom:20px}@media print{button{display:none}body{margin:20mm}@page{size:letter;margin:0}}</style></head><body><button onclick="window.print()">Imprimir / Guardar como PDF</button><header><span class="folio">${xml(folio(b))}</span><b>${xml(name)}</b><h1>${b.status==='waiting'?'Solicitud en lista de espera':'Confirmación de cita'}</h1><span>${xml(stateName(b.status))}</span></header><dl><dt>Cliente</dt><dd>${xml(b.client)}</dd><dt>Fecha y horario · Ciudad de México</dt><dd>${xml(b.date)} · ${xml(b.time)}–${clock(minutes(b.time)+b.duration)} (${b.duration} min)</dd><dt>Sala / personas totales</dt><dd>${xml(roomName(b.room))} · ${b.people} personas</dd><dt>Atiende</dt><dd>${xml(b.attendeeName)} · ${xml(b.teamName)}</dd><dt>Operaciones</dt><dd>${b.operations.map((o:any)=>xml(o.name)).join('<br>')}</dd>${b.accessibility?'<dt>Accesibilidad</dt><dd>Prioridad por discapacidad solicitada</dd>':''}</dl><footer>Folio ${xml(folio(b))} · Agendó ${xml(b.createdBy)} · ${b.status==='waiting'?'Esta solicitud aún no tiene sala confirmada.':'Conserva este comprobante para identificar tu cita.'}</footer><script>window.onload=()=>setTimeout(()=>window.print(),200)<\/script></body></html>`);w.document.close();return true;
}
